version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: naapuriapu-postgres
    environment:
      POSTGRES_USER: naapuriapu
      POSTGRES_PASSWORD: naapuriapu
      POSTGRES_DB: naapuriapu
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
